language: generic
sudo: required
services:
    - docker
before_install:
    - docker build -t nithin/test-react-nithin -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true nithin/test-react-nithin npm run test -- --coverage
after_success:
    - docker build -t nithin/multi-client ./client
    - docker build -t nithin/multi-nginx ./nginx
    - docker build -t nithin/multi-server ./server
    - docker build -t nithin/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push nithin/multi-client
    - docker push nithin/multi-nginx
    - docker push nithin/multi-server
    - docker push nithin/multi-worker
deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-nithin"
  env: "DockerReactNithin-env"
  bucket_name: "elasticbeanstalk-us-east-1-615254007828"
  bucket_path: "docker-react-nithin"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY